services:
  db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: sonarDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  cb:
    restart: unless-stopped
    image: redis:alpine
    expose:
      - 6379
    ports:
      - "6379:6379"

volumes:
  postgres-data:
  cache: